model_id: segment_anything_2
display_name: "Segment Anything 2.1"

params:
  model_cfg: "sam2.1_hiera_b+"  # options: [sam2.1_hiera_l, sam2.1_hiera_s, sam2.1_hiera_t]
  model_path: "sam2.1_hiera_base_plus.pt"
  device: "cuda:0"
  show_boxes: false
  show_masks: true
  multimask_output: false
  epsilon_factor: 0.001
  cache_size: 10  # LRU cache size for image embeddings

widgets:
  - name: button_add_point
    value: null
  - name: button_remove_point
    value: null
  - name: button_add_rect
    value: null
  - name: button_clear
    value: null
  - name: button_finish_object
    value: null
  - name: mask_fineness_slider
    value: 10
  - name: mask_fineness_value_label
    value: null